name: Testing Demo

#If event is set as Workflow-dispatch then it will trigger manually not automatically 
on: 
  workflow_dispatch:

# this varIABles can be used in single workflow only  
env:
  Greeting: hello
jobs:
  Called_Wf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: testing command
        run: echo "i am called workflow - I am printing env varaiable value- $Greeting"
