name: Testing Demo

#If event is set as Workflow-dispatch then it will trigger manually not automatically 
on: 
  workflow_dispatch:

# this varIABles can be used in single workflow only  
# FOR variables to be acess across multiple WF then we create configuration value in settings and use in this format ${{vars.PROJECT_ID}}
env:
  Greeting: hello
jobs:
  Called_Wf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: testing command
        run: echo "i am called workflow - I am printing env varaiable value- $Greeting and my configuration value is coming from - ${{vars.PROJECT_ID}}"
  context-varables:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: testing context varaibles
        run: |
          echo "repository name : ${{github.repository}}"
