name: hello

#if something is pushed into the repository, that is the action on which it triggers
'on': pull
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "hello world"
